const collegeNameConverter = {
    문과대학: "Liberal_Arts",
    상경대학: "Commerce_and_Economics",
    경영대학: "Business",
    이과대학: "Science",
    공과대학: "Engineering",
    생명시스템대학: "Life_Science_and_Biotechnology",
    신과대학: "Theology",
    사회과학대학: "Social_Sciences",
    법학대학: "Law",
    음악대학: "Music",
    생활과학대학: "Human_Ecology",
    교육과학대학: "Educational_Science",
    학부대학: "University_College",
    언더우드국제대학: "Underwood_International_College",
    글로벌인재대학: "Global_Leadership_Division",
    의과대학: "Medicine",
    치과대학: "Dentistry",
    간호대학: "Nursing",
    약학대학: "Pharmacy",
};
